### ISSUE TITLE
Assume all species not labeled as target or conserved will be outgroup?

### ISSUE THREAD

**Issue by gwct** [harvardinformatics/PhyloAcc-interface#2]
The PhyloAcc config file has settings for species that are to be labeled as 'targets', 'conserved', and 'outgroup'. In the [ratite example](https://github.com/xyz111131/PhyloAcc/blob/627dda131f34f9a02d4b1497e245bf90d1bd3124/Simulation_ratite/param2-1-test.txt), all species in the input phylogeny are represented in one of these three lists. Is it safe to assume that all species will always be listed as such? If so, we can get rid of the outgroup specification in the front-end and just assume all species not listed as targets or conserved will be in the outgroup.

**Comment by HanY-H** [comment]
yes, any species will be in one of the 3 groups. But we will need to amend the c++ code accordingly if we are going to infer the set of species in outgroup from the input.

**Comment by gwct** [comment]
Ok great! And I don't necessarily think there's a reason to alter the C++ code for this -- we can infer the outgroups easily from Python and have it write the config file as PhyloAcc normally expects it. But I guess that touches on the larger point of how we expect the Python interface and the C++ codebases to interact with each other. For now, I was just going to have Python write the normal config file to minimize changes to the C++ code, but I'm definitely open to other ideas!

**Comment by tsackton** [comment]
For now I think we should minimize required changes to the C++ code base, and if we do make changes it would probably be to improve ease of installation and speed first. But this might be a good subject for another discussion once the Python front end is a little further along and we have a better sense of what might be reasonable changes to push to the C++ code.

**Comment by xyz111131** [comment]
I was thinking of further extension of the code with more categories, e.g. nondetermined species, so I didn't let C++ code infer the rest of species. I agree that we could change the Python front-end. But I think it'd be better to let the user specify target and outgroup species, and set the rest of the species as conserved group, since the conserved species is larger group in the usual cases.

**Comment by gwct** [comment]
Agreed, we want to try and minimize the amount of info the user has to type into the command line. Given that, I think I will design the python code to work in the following ways:

1. The user can provide any 2 of the 3 groups and the third will be inferred as all remaining species. If the number of groups are expanded to N groups in the future, we can easily expand the required number of groups the user provides to N-1 as long as all species are required to be in one of the groups.
2. Species can be provided by their tip labels (as they are now), but if any number of the tips form a monophyletic clade, the user can also pre-label the internal node of that clade's common ancestor and we can get all tips descending from that labeled node. Multiple internal nodes for different clades can be entered. This could really help minimize the amount of stuff to type.
3. In assistance to point 2, we can add a `--labeltree` option to the front-end as a pre-run step that automatically labels the internal nodes of the input tree.

All of this will be handled by the Python front-end and translated into the config file for the main codebase. Let me know if you see any problems with this approach!

**Comment by tsackton** [comment]
Relevant to Gregg's point 1, which of these categories are actually required? I think at least conceptually, neither outgroups or accelerated groups are required, although the restricted model will be identical to the null model if there are no targets and thus running PhyloAcc with no targets is a little pointless. 

This actually brings up a larger point, which is that a user may often want to compute more than three models, e.g., a null (no species can be accelerated), alternate 1 (species ww-xx accelerated), alternate 2 (species yy-zz accelerated), full (all species potentially accelerated). As I understand it, this is right now is difficult to do efficiently, as if you run PhyloAcc twice with a different set of target accelerated species but with the same tree and neutral model, you will compute identical null and unrestricted models with both runs.

This change -- allowing PhyloAcc to be run in a way that avoids this issue -- probably needs to be implemented in the C++ code, not the Python front end. But to preserve flexibility to implement something like this in the future, I agree with Zhirui we should just ask the user to provide the species that are not conserved. That is, I would propose that the Python front end just take a ```--targets``` (or similar name) and an ```--outgroups``` option, and assume all species not specified in either of these options are conserved. Ideally the Python code could accept either a typed list containing tip labels, internal nodes, or a mix, or a file with the same information.

I would then make the ```--outgroups``` option optional, but for now throw an error if ```--targets``` doesn't contain at least one species. Later if we implement a two-model (null and unrestricted) version of PhyloAcc then we could remove the requirement for at least one target. Then if we implement additional (probably optional) categories, these could be added as additional options? 

Does this seem sensible?

**Comment by tsackton** [comment]
If outgroups isn't present, assume that everything not in targets is conserved.

**Comment by gwct** [comment]
A quick check confirms that `OUTGROUP` is an optional line in the main config file.

**Comment by gwct** [comment]
Closing this with the final comments:

1. Outgroup is not a required group but Conserved and Targets are.
2. Only 2 of the 3 groups need to be specified in the interface and the third will be inferred
3. The number of groups may be expanded in the future to test multiple models against the null and full (this probably deserves its own issue)
