### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by xzk-fd** [harvardinformatics/PhyloAcc-interface#20]
Hi，I am trying to install the tools following the bulid.sh and Makefile,i had installed gsl and armadillo by conda firstly , then 

>$make
$CXX is [g++-7]
$PREFIX is []
$GSL_INCLUDE is [/include/]
$GSL_LIB is [/lib/]
g++-7 -Wall -g -O2 -std=c++11 -I/include/ -L/lib/ src/PhyloAcc/SRC/*.cpp -o PhyloAcc -lgsl -lm -lgslcblas -larmadillo -fopenmp
/bin/sh: g++-7: command not found
make: *** [Makefile:50: PhyloAcc] Error 127

my GCC version is 9.4, so i delete "-7" in Makefile, then

> $make
$CXX is [g++]
$PREFIX is []
$GSL_INCLUDE is [/include/]
$GSL_LIB is [/lib/]
g++ -Wall -g -O2 -std=c++11 -I/include/ -L/lib/ src/PhyloAcc/SRC/*.cpp -o PhyloAcc -lgsl -lm -lgslcblas -larmadillo -fopenmp
In file included from src/PhyloAcc/SRC/bpp_c2.cpp:9:
src/PhyloAcc/SRC/bpp_c.hpp:14:10: fatal error: gsl/gsl_rng.h: No such file or directory
   14 | #include <gsl/gsl_rng.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
In file included from src/PhyloAcc/SRC/bpp_c.cpp:9:
src/PhyloAcc/SRC/bpp_c.hpp:14:10: fatal error: gsl/gsl_rng.h: No such file or directory
   14 | #include <gsl/gsl_rng.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
In file included from src/PhyloAcc/SRC/bpp.cpp:9:
src/PhyloAcc/SRC/bpp.hpp:13:10: fatal error: gsl/gsl_rng.h: No such file or directory
   13 | #include <gsl/gsl_rng.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
src/PhyloAcc/SRC/main.cpp:18:10: fatal error: armadillo: No such file or directory
   18 | #include <armadillo>
      |          ^~~~~~~~~~~
compilation terminated.
In file included from src/PhyloAcc/SRC/newick.cpp:4:
src/PhyloAcc/SRC/newick.h:6:10: fatal error: armadillo: No such file or directory
    6 | #include <armadillo>
      |          ^~~~~~~~~~~
compilation terminated.
make: *** [Makefile:50: PhyloAcc] Error 1

I had installed gsl by source code and can find the file named gsl_rng.h , but it doesn't work, could you give me some help, thank you.

**Comment by xzk-fd** [comment]
thanks for your early replay!
i had installed phyloacc by conda, but i can't use phyloacc_post.py to deal with the result, so i wanted to install PhyloAcc-interface, but i faced the problem

$conda install phyloacc
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.

Retrieving notices: ...working... done



At 2022-09-01 00:05:05, "Gregg Thomas" ***@***.***> wrote:

Hello,
Sorry about this, but this repo and these instructions are not up to date. Our current version of PhyloAcc is here: https://phyloacc.github.io/

This can now be installed with conda, so please try that and if you are still having problems feel free to open another issue on the new repo here: https://github.com/phyloacc/PhyloAcc

I will go ahead and update the readme of this repo to point to the updated website.

**Comment by gwct** [comment]
Ah, I understand. Yes it looks like it is already installed, but unfortunately I didn't include the `phyloacc_post.py` script in the bioconda build. See [this issue on the PhyloAcc github](https://github.com/phyloacc/PhyloAcc/issues/37) for a possible workaround while I get that in the build.

**Comment by xzk-fd** [comment]
thank you for your help! And i have another question after i  run phyloacc_post.py







the result fold as follow




could you give me some help?










At 2022-09-01 23:48:28, "Gregg Thomas" ***@***.***> wrote:

Ah, I understand. Yes it looks like it is already installed, but unfortunately I didn't include the phyloacc_post.py script in the bioconda build. See this issue on the PhyloAcc github for a possible workaround while I get that in the build.

**Comment by gwct** [comment]
Sorry, it looks like whatever you tried to include didn't attach. I just see a lot of blank lines. If it is easier to email me directly, feel free to do so. My email is posted on my website here: https://gwct.github.io/

**Comment by xzk-fd** [comment]
I'm sorry to hear about that. I have sent email to ***@***.***
If it have any other questions, please let me know.
thank you for you help again!



At 2022-09-03 01:04:52, "Gregg Thomas" ***@***.***> wrote:

Sorry, it looks like whatever you tried to include didn't attach. I just see a lot of blank lines. If it is easier to email me directly, feel free to do so. My email is posted on my website here: https://gwct.github.io/
